
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Mitanin Heat Desk local demo

Resources:
  HeatDeskFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: build/pkg/
      Handler: handler.handler
      Runtime: python3.12
      Timeout: 30
      MemorySize: 256
